AWSTemplateFormatVersion: 2010-09-09
Description: First time deploying with CloudFormation

Parameters:
  LambdaDefaultRole:
    Description: Basic execution role
    Type: String

Resources:
  ParentLambdaFunction:
    Type: AWS::Lambda::Function
    Properties:
      Description: An attempt to chain 2 lambda calls (PARENT)
      FunctionName: ParentFunction
      Handler: index.handler
      MemorySize: 128
      Role: !Ref LambdaDefaultRole
      Runtime: python3.9
      Timeout: 5
      Environment:
        Variables:
          CHILD_LAMBDA_ARN: !GetAtt ChildLambdaFunction.Arn
      Code: ./out/parent_function.zip

  ChildLambdaFunction:
    Type: AWS::Lambda::Function
    Properties:
      Description: An attempt to chain 2 lambda calls (CHILD)
      FunctionName: ChildFunction
      Handler: index.handler
      MemorySize: 128
      Role: !Ref LambdaDefaultRole
      Runtime: python3.9
      Timeout: 5
      Code: ./out/child_function.zip
